version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      tarojs:
        patterns:
          - '@tarojs*'
          - 'eslint-config-taro'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
      commitlint:
        patterns:
          - '@commitlint*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
