#!/bin/bash
set -e

pnpm exec unbuild packages/shared
pnpm exec unbuild packages/helper
pnpm exec unbuild packages/store
pnpm exec unbuild packages/extends
pnpm exec unbuild packages/hooks
pnpm exec unbuild packages/components
