#!/bin/bash
set -e

cmd() {
  echo
  echo 🟢 $*
  $*
}

# temporarily fix the compilation issue: "Template `tmpl_0_66` not found"
patch() {
  local target=${1-undefined}
  local path=examples/$target/dist/base.wxml

  if [ ! "$(grep "tmpl_0_66" $path)" ]; then
    echo "append template \`tmpl_0_66\` in $path"
    cat >>$path <<EOF

<template name="tmpl_0_66">
  <web-view src="{{i.p0}}" bindmessage="eh" bindload="eh" binderror="eh" style="{{i.st}}" class="{{i.cl}}" bindtap="eh"  id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
    <block wx:for="{{i.cn}}" wx:key="sid">
      <template is="{{xs.a(c, item.nn, l)}}" data="{{i:item,c:c+1,l:xs.f(l,item.nn)}}" />
    </block>
  </web-view>
</template>
EOF
  fi
}

release() {
  local target=${1-undefined}
  local dir=./examples/$target
  local mode=${2-dev}
  local name=$(node -p "require(\"$dir/package.json\").name")
  local version=$(node -p "require(\"$dir/package.json\").version")

  export CI_MINI_VERSION="$name@$version"
  export CI_MINI_DESC="Release $name v$version"
  export CI_MINI_ROBOT=2

  cmd pnpm --dir $dir run clean
  cmd pnpm --dir $dir exec taro prebuild --type weapp --mode=$mode
  cmd pnpm --dir $dir exec taro build --type weapp --mode=$mode
  cmd patch $target
  cmd pnpm --dir $dir exec taro upload --type weapp --mode=$mode
}

case $1 in
release)
  $1 $2 $3
  ;;
patch)
  $1 $2
  ;;
*)
  echo "unknown command"
  exit 1
  ;;
esac
