#!/bin/bash
set -e

cmd() {
  echo
  echo 🟢 $*
  $*
}

patch() {
  local target=${1-undefined}

  # temporarily fix the compilation issue: "Template `tmpl_0_66` not found"
  local template=examples/$target/dist/base.wxml
  if [ ! "$(grep "tmpl_0_66" $template)" ]; then
    echo "append template \`tmpl_0_66\` in $template"
    cat >>$template <<EOF

<template name="tmpl_0_66">
  <web-view src="{{i.p0}}" bindmessage="eh" bindload="eh" binderror="eh" style="{{i.st}}" class="{{i.cl}}" bindtap="eh"  id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
    <block wx:for="{{i.cn}}" wx:key="sid">
      <template is="{{xs.a(c, item.nn, l)}}" data="{{i:item,c:c+1,l:xs.f(l,item.nn)}}" />
    </block>
  </web-view>
</template>
EOF
  fi
}

release() {
  local target=${1-undefined}
  local opts="--mode=${2-dev} --type ${3-weapp}"
  local dir=./examples/$target
  local name=$(node -p "require(\"$dir/package.json\").name")
  local version=$(node -p "require(\"$dir/package.json\").version")

  export CI_MINI_VERSION="$name@$version"
  export CI_MINI_DESC="Release $name v$version"
  export CI_MINI_ROBOT=2

  cmd pnpm --dir $dir run clean
  cmd pnpm --dir $dir exec taro prebuild $opts
  cmd pnpm --dir $dir exec taro build $opts
  cmd patch $target
  cmd pnpm --dir $dir exec taro upload $opts
}

case $1 in
release | patch)
  $1 $2 $3
  ;;
*)
  echo "unknown command"
  exit 1
  ;;
esac
