#!/bin/bash
set -e

path=examples/taro-app/dist/base.wxml

# temporarily fix the compilation issue: "Template `tmpl_0_66` not found"
if [ ! "$(grep "tmpl_0_66" $path)" ]; then
  echo "append template \`tmpl_0_66\` in $path"
  cat >>$path <<EOF

<template name="tmpl_0_66">
  <web-view src="{{i.p0}}" bindmessage="eh" bindload="eh" binderror="eh" style="{{i.st}}" class="{{i.cl}}" bindtap="eh"  id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
    <block wx:for="{{i.cn}}" wx:key="sid">
      <template is="{{xs.a(c, item.nn, l)}}" data="{{i:item,c:c+1,l:xs.f(l,item.nn)}}" />
    </block>
  </web-view>
</template>
EOF
fi
