#!/bin/bash
set -e

# check build
pnpm build

npm version ${1-patch}
version=$(node -p 'require("./package.json").version')
pnpm --parallel -r exec npm version $version

git add .
git commit -m "chore(release): v$version"
git tag -a v$version -m "chore(release): v$version"
git push --follow-tags
