#!/bin/bash
set -e

# check build
pnpm build

v=${1-patch}

npm version $v
version=$(node -p 'require("./package.json").version')
pnpm --parallel -r exec npm version $version

pnpm exec conventional-changelog -p angular -t v -i CHANGELOG.md -s

git add .
git commit -m "chore(release): v$version"
git tag -a v$version -m "chore(release): v$version"
git push --follow-tags
