#!/bin/bash
set -e

mode=${1-dev}
type=${2-weapp}

cmd() {
  echo
  echo 🟢 $*
  $*
}

cmd pnpm build

cmd cd miniapp/template

name=$(node -p 'require("./package.json").name')
version=$(node -p 'require("./package.json").version')

export CI_MINI_VERSION="$name@$version"
export CI_MINI_DESC="Release $name v$version"
export CI_MINI_ROBOT=2

cmd pnpm clean
cmd pnpm taro prebuild --type $type --mode=$mode
cmd pnpm taro build --upload --type $type --mode=$mode
cd -
