#!/bin/bash
set -e

mode=${1-dev}
type=${2-weapp}

cmd() {
  echo
  echo 🟢 $*
  $*
}

dir=./examples/taro-app
name=$(node -p "require(\"$dir/package.json\").name")
version=$(node -p "require(\"$dir/package.json\").version")

export CI_MINI_VERSION="$name@$version"
export CI_MINI_DESC="Release $name v$version"
export CI_MINI_ROBOT=2

cmd pnpm --dir $dir run clean
cmd pnpm --dir $dir exec taro prebuild --type $type --mode=$mode
cmd pnpm --dir $dir exec taro build --type $type --mode=$mode
cmd "$(dirname $0)/patch-template"
cmd pnpm --dir $dir exec taro upload --type $type --mode=$mode
