name: 'ci'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Run lint
        run: |
          pnpm exec eslint packages/ --ext .ts,tsx
          pnpm exec stylelint "packages/**/*.{scss,css}"
          pnpm exec prettier --check .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Check build
        run: pnpm build --dev

      - name: Check types (packages/example)
        run: pnpm --dir=packages/example exec tsc --noEmit

      - name: Run unit tests
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-example:
    strategy:
      matrix:
        platform: [weapp, alipay] # skip 'tt', wait for RootPortal import issue to be resolved.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - run: pnpm --dir packages/example run build:${{ matrix.platform }}
