name: 'ci'

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  lint:
    if: ${{ !(startsWith(github.event.head_commit.message, 'chore(release)')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Run lint
        run: |
          pnpm exec eslint ./ --ext .ts,tsx
          pnpm exec stylelint "{packages,examples}/**/*.{scss,css}"
          pnpm exec prettier --check .

  test:
    if: ${{ !(startsWith(github.event.head_commit.message, 'chore(release)')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Check build
        run: pnpm build --dev

      - name: Check examples
        run: pnpm --filter "./examples/*" exec tsc --noEmit

      - name: Run unit tests
        run: pnpm test

      - name: Upload coverage reports to Codecov
        run: |
          # codecov cli
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          # upload flags one by one
          for dir in ./packages/*; do
            if [ -d "$dir/coverage/" ]; then
              ./codecov -t ${CODECOV_TOKEN} -F $(basename $dir) -f $dir/coverage/coverage-final.json
            fi
          done
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-example:
    if: ${{ !(startsWith(github.event.head_commit.message, 'chore(release)')) }}
    strategy:
      matrix:
        platform: [weapp, alipay, tt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm build

      - run: pnpm --filter "./examples/*" run build:${{ matrix.platform }}
